### ISSUE TITLE
Не можем подружить Rustroe Billing SDK с myTarget SDK.

### ISSUE THREAD

**Issue by Prog-Maker** [myTargetSDK/mytarget-unity#8]
Суть проблемы - Есть приложение Unity. Делаем для Rustroe. Значит интегрировали Rustroe billing SDK и myTarget SDK. Пока не было рекламного у нас все работало. Покупки работали, восстановление покупок работало. Но когда поставили еще myTarget sdk начались проблемы. Покупки перестают восстанавливаться, Это было unity 2021. перешли на Unity 2022 - покупки заработали, восстановление заработало, но реклама перестала грузиться. т.е. в консоли я вижу, реклама создается - [mytargte.unirt] : MyTarget Unity [1.3.1] RewardedAd is created. Но метод _rewardedAd.Load()  просто не вызывается. Я смотрел через логкат - вызова не происходит. Без сдк рустора  все начинает работать.

**Comment by Prog-Maker** [comment]
Rustore Billing SDK 5.0.2
MyTarget SDK - 1,3,1
Unity 2021.3.35f1 / Unity 2022.3.30f1

**Comment by Zaakk** [comment]
Мы готовим обновление SDK для Unity
