### ISSUE TITLE
AndroidJavaException: java.lang.NoSuchMethodError: no non-static method with name='setIcqIds' signature='()V' in class Lcom.my.target.common.CustomParams;

### ISSUE THREAD

**Issue by SERbIY93** [myTargetSDK/mytarget-unity#9]
Добрый день!
Реклама MyTarget не работает. Подскажите, пожалуйста, в чём может быть проблема?
При попытке произвести загрузку рекламного баннера и интерстишл - появляется ошибка в Java клссе.
Unity: 2022.3.42
MyTarget Unity SDK: 1.3.1
Android target API: 34
Лог с устройства:

Debug [myTarget] Debug mode enabled
Info Unity [mytarget.unity]: MyTarget.Unity(1.3.1): InterstitialAd is created
Info Unity Mycom.Target.Unity.Ads.InterstitialAd:.ctor(UInt32)
Info Unity ADSManager:CreateInterstitialAd()
Info Unity 
Info Unity [mytarget.unity]: MyTarget.Unity(1.3.1): MyTargetView is created
Info Unity Mycom.Target.Unity.Ads.MyTargetView:.ctor(UInt32, AdSize, Boolean)
Info Unity ADSManager:LoadBannerAd()
Info Unity 
Info [myTarget] Interstitial ad created. Version - 5.15.3
Debug [myTarget] CustomParams: Age param removed
Debug [myTarget] CustomParams: Gender param removed
Debug Unity Uploading Crash Report

Error Unity AndroidJavaException: java.lang.NoSuchMethodError: no non-static method with name='setIcqIds' signature='()V' in class Ljava.lang.Object;
Error Unity java.lang.NoSuchMethodError: no non-static method with name='setIcqIds' signature='()V' in class Ljava.lang.Object;
Error Unity 	at com.unity3d.player.ReflectionHelper.getMethodID(Unknown Source:241)
Error Unity 	at com.unity3d.player.ReflectionHelper.nativeProxyInvoke(Native Method)
Error Unity 	at com.unity3d.player.ReflectionHelper.-$$Nest$smnativeProxyInvoke(Unknown Source:0)
Error Unity 	at com.unity3d.player.ReflectionHelper$a.invoke(Unknown Source:75)
Error Unity 	at java.lang.reflect.Proxy.invoke(Proxy.java:1006)
Error Unity 	at $Proxy2.run(Unknown Source)
Error Unity 	at android.os.Handler.handleCallback(Handler.java:873)
Error Unity 	at android.os.Handler.dispatchMessage(Handler.java:99)
Error Unity 	at android.os.Looper.loop(Looper.java:214)
Error Unity 	at android.app.ActivityThread.main(ActivityThread.java:7078)
Error Unity 	at java.lang.reflect.Method.invoke(Native Method)
Error Unity 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
Error Unity 	at com.android.internal.os.Zyg

Info [myTarget] MyTargetView created. Version - 5.15.3
Debug [myTarget] MyTargetView: Initialized
Debug [myTarget] CustomParams: Age param removed
Debug [myTarget] CustomParams: Gender param removed
Debug Unity Curl error 7: Failed to connect to config.uca.cloud.unity3d.com port 443 after 90 ms: Error
Debug Unity Uploading Crash Report

Error Unity AndroidJavaException: java.lang.NoSuchMethodError: no non-static method with name='setIcqIds' signature='()V' in class Lcom.my.target.common.CustomParams;
Error Unity java.lang.NoSuchMethodError: no non-static method with name='setIcqIds' signature='()V' in class Lcom.my.target.common.CustomParams;
Error Unity 	at com.unity3d.player.ReflectionHelper.getMethodID(Unknown Source:241)
Error Unity 	at com.unity3d.player.ReflectionHelper.nativeProxyInvoke(Native Method)
Error Unity 	at com.unity3d.player.ReflectionHelper.-$$Nest$smnativeProxyInvoke(Unknown Source:0)
Error Unity 	at com.unity3d.player.ReflectionHelper$a.invoke(Unknown Source:75)
Error Unity 	at java.lang.reflect.Proxy.invoke(Proxy.java:1006)
Error Unity 	at $Proxy2.run(Unknown Source)
Error Unity 	at android.os.Handler.handleCallback(Handler.java:873)
Error Unity 	at android.os.Handler.dispatchMessage(Handler.java:99)
Error Unity 	at android.os.Looper.loop(Looper.java:214)
Error Unity 	at android.app.ActivityThread.main(ActivityThread.java:7078)
Error Unity 	at java.lang.reflect.Method.invoke(Native Method)
Error Unity 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:49

**Comment by integer222** [comment]
Удалось решить проблему ?

**Comment by SERbIY93** [comment]
Нет, я просто поменял рекламное SDK на Unity Ads

**Comment by Zaakk** [comment]
Мы планируем обновление в ближайшее время, разумеется с исправлением ошибки

**Comment by zxt385189207** [comment]
Has it been updated? Has it been fixed?
